batch_size: 128
class_names:
- airplane
- automobile
- bird
- cat
- deer
- dog
- frog
- horse
- ship
- truck
data_dir: data
image_size: !!python/tuple
- 32
- 32
in_channels: 3
mean: !!python/tuple
- 0.4914
- 0.4822
- 0.4465
name: CIFAR10
num_classes: 10
num_workers: 4
patch_size: 4
persistent_workers: true
pin_memory: true
std: !!python/tuple
- 0.247
- 0.2435
- 0.2616
