batch_size: 128
best_model_name: best_model.pth
checkpoint_dir: checkpoints
early_stopping_patience: 15
grad_accum_steps: 4
gradient_clip_val: 0.5
label_smoothing: 0.1
learning_rate: 0.001
log_interval: 10
num_epochs: 1
optimizer: AdamW
router_loss_weight: 0.1
scheduler: cosine_warmup
use_amp: true
use_gradient_checkpointing: true
warmup_epochs: 5
warmup_ratio: 0.1
weight_decay: 0.01
