cmap_attention: hot
cmap_confusion: Blues
cmap_heatmap: viridis
confusion_matrix_fig_size: !!python/tuple
- 10
- 8
dpi: 300
expert_regions_fig_size: !!python/tuple
- 15
- 5
expert_usage_fig_size: !!python/tuple
- 10
- 6
num_images_grid: 5
num_samples_attention: 5
num_samples_router: 5
num_samples_tokens: 5
overlay_alpha: 0.5
save_dir: visualizations
single_prediction_fig_size: !!python/tuple
- 6
- 8
